// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Keyboard from "./Keyboard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Chess Visualization",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx(Keyboard.make, {
                      onSubmit: (function (sq) {
                          console.log(sq);
                        })
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Keyboard Not a pure module */
