// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chess from "./Chess.res.mjs";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as SquareColorPicker from "./SquareColorPicker.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(Chess.randomSquare);
  var setSquare = match[1];
  var square = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setHistory = match$1[1];
  var pushHistory = function (item) {
    setHistory(function (h) {
          return Belt_Array.concatMany([
                      h,
                      [item]
                    ]);
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "What color is this square?",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Record so far:",
                      className: "text-2xl font-semibold mt-8 mb-4"
                    }),
                JsxRuntime.jsx("p", {
                      children: match$1[0].join(" "),
                      className: "text-xl"
                    }),
                JsxRuntime.jsx("h2", {
                      children: Chess.string_of_square(square),
                      className: "text-xl mt-4 mb-8"
                    }),
                JsxRuntime.jsx(SquareColorPicker.make, {
                      onPick: (function (squareColor) {
                          pushHistory(squareColor === Chess.color_of_square(square) ? "✅" : "❌");
                          setSquare(function (param) {
                                return Chess.randomSquare();
                              });
                        })
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Chess Not a pure module */
