// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Math from "@rescript/core/src/Core__Math.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var ranks = Belt_Array.range(1, 8);

var files = [
  /* 'a' */97,
  /* 'b' */98,
  /* 'c' */99,
  /* 'd' */100,
  /* 'e' */101,
  /* 'f' */102,
  /* 'g' */103,
  /* 'h' */104
];

function fromChar(c) {
  return String.fromCharCode(c);
}

function randomSquare() {
  var rankIndex = Core__Math.Int.random(0, ranks.length);
  var fileIndex = Core__Math.Int.random(0, files.length);
  return [
          files[fileIndex],
          ranks[rankIndex]
        ];
}

function string_of_square(param) {
  return String.fromCharCode(param[0]) + param[1].toString();
}

function color_of_square(param) {
  var fileIndex = Core__Option.getExn(Core__Array.indexOfOpt(files, param[0]), undefined);
  var rankIndex = Core__Option.getExn(Core__Array.indexOfOpt(ranks, param[1]), undefined);
  if (fileIndex % 2 === rankIndex % 2) {
    return "Dark";
  } else {
    return "Light";
  }
}

export {
  ranks ,
  files ,
  fromChar ,
  randomSquare ,
  string_of_square ,
  color_of_square ,
}
/* ranks Not a pure module */
