// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Chess from "./Chess.res.mjs";
import * as React from "react";
import * as TileButton from "./TileButton.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var nbsp = "\u00A0";

function Keyboard(props) {
  var onSubmit = props.onSubmit;
  var match = React.useState(function () {
        return "Nothing";
      });
  var setPhase = match[1];
  var phase = match[0];
  var tmp;
  tmp = typeof phase !== "object" ? nbsp : (
      phase.TAG === "File" ? Chess.fromChar(phase._0) : Chess.fromChar(phase._0) + phase._1.toString()
    );
  var tmp$1;
  if (typeof phase !== "object") {
    tmp$1 = Chess.files.map(function (n) {
          var ns = Chess.fromChar(n);
          return JsxRuntime.jsx(TileButton.make, {
                      children: Caml_option.some(ns),
                      className: "aspect-video",
                      onClick: (function (param) {
                          setPhase(function (param) {
                                return {
                                        TAG: "File",
                                        _0: n
                                      };
                              });
                        })
                    }, ns);
        });
  } else if (phase.TAG === "File") {
    var file = phase._0;
    tmp$1 = Chess.ranks.map(function (rank) {
          var rankS = String(rank);
          return JsxRuntime.jsx(TileButton.make, {
                      children: Caml_option.some(rankS),
                      className: "aspect-video",
                      onClick: (function (param) {
                          setPhase(function (param) {
                                return {
                                        TAG: "Rank",
                                        _0: file,
                                        _1: rank
                                      };
                              });
                        })
                    }, rankS);
        });
  } else {
    tmp$1 = Chess.ranks.map(function (rank) {
          return JsxRuntime.jsx(TileButton.make, {
                      children: Caml_option.some(nbsp),
                      className: "aspect-video",
                      disabled: true
                    }, String(rank));
        });
  }
  var onClick;
  if (typeof phase !== "object" || phase.TAG === "File") {
    onClick = undefined;
  } else {
    var rank = phase._1;
    var file$1 = phase._0;
    onClick = (function (param) {
        onSubmit(Chess.fromChar(file$1) + rank.toString());
      });
  }
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx("p", {
                      children: tmp,
                      className: "text-2xl"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        tmp$1,
                        JsxRuntime.jsx(TileButton.make, {
                              children: "⌫",
                              className: "aspect-video",
                              onClick: (function (_event) {
                                  setPhase(function (phase) {
                                        if (typeof phase !== "object" || phase.TAG === "File") {
                                          return "Nothing";
                                        } else {
                                          return {
                                                  TAG: "File",
                                                  _0: phase._0
                                                };
                                        }
                                      });
                                })
                            }, "⌫")
                      ],
                      className: "grid grid-cols-3 max-w-md border-solid border-2 border-b-0 border-sky-50 text-xl"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(TileButton.make, {
                            children: "Enter",
                            className: "h-20",
                            disabled: Core__Option.isNone(onClick),
                            onClick: onClick
                          }),
                      className: "max-w-md border-solid border-2 border-sky-50 border-t-0"
                    })
              ]
            });
}

var make = Keyboard;

export {
  make ,
}
/* Chess Not a pure module */
