// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TileButton from "./TileButton.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function SquareColorPicker(props) {
  var onPick = props.onPick;
  return JsxRuntime.jsx("div", {
              children: [
                  "Dark",
                  "Light"
                ].map(function (color) {
                    var colorString;
                    colorString = color === "Dark" ? "Dark" : "Light";
                    var className;
                    className = color === "Dark" ? " bg-gray-900 text-white hover:bg-gray-700 " : " text-black ";
                    return JsxRuntime.jsx(TileButton.make, {
                                children: Caml_option.some(colorString),
                                className: "aspect-video " + className,
                                onClick: (function (param) {
                                    onPick(color);
                                  })
                              }, colorString);
                  }),
              className: "grid grid-cols-2 max-w-md border-solid border-2 border-b-0 border-sky-50 text-xl"
            });
}

var make = SquareColorPicker;

export {
  make ,
}
/* TileButton Not a pure module */
